/**
 * 
 */
package com.apaulin.http;

/**
 * Class representing the RPC sessions
 * @author Anthony Paulin
 * @version 0.1
 * @since 06-01-2020
 * @category RPC
 *
 */
public class RpcSession {
	
	private int id;
	private boolean transactionInProgress = false; 
	private int transactionId = 0;//ID generated by RPC when a transaction has been requested.
	private boolean commitValidated = false;//Check if the commit has been validated before a commit
	private RpcRequest req;
	
	public RpcSession(int id,RpcRequest req) {
		this.id = id;
		this.req = req;
	}
	
	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}
	/**
	 * @return the transactionInProgress
	 */
	public boolean isTransactionInProgress() {
		return transactionInProgress;
	}
	/**
	 * @param transactionInProgress the transactionInProgress to set
	 */
	public void setTransactionInProgress(boolean transactionInProgress) {
		this.transactionInProgress = transactionInProgress;
	}
	/**
	 * @return the transactionId
	 */
	public int getTransactionId() {
		return transactionId;
	}
	/**
	 * @param transactionId the transactionId to set
	 */
	public void setTransactionId(int transactionId) {
		this.transactionId = transactionId;
	}
	/**
	 * @return the commitValidated
	 */
	public boolean isCommitValidated() {
		return commitValidated;
	}
	/**
	 * @param commitValidated the commitValidated to set
	 */
	public void setCommitValidated(boolean commitValidated) {
		this.commitValidated = commitValidated;
	}
	/**
	 * @return the req
	 */
	public RpcRequest getReq() {
		return req;
	}
	/**
	 * @param req the req to set
	 */
	public void setReq(RpcRequest req) {
		this.req = req;
	}
	
}
